management:
  endpoints:
    web:
      exposure:
        include: prometheus,health

spring:
  kafka:
    consumer:
      group-id: gxf-soap-bridge
  threads:
    virtual:
      enabled: true

soap:
  hostname-verification-strategy: BROWSER_COMPATIBLE_HOSTNAMES

kafka:
  incoming:
    requests:
      concurrency: 1
    responses:
      concurrency: 1
