logging:
  level:
    org:
      gxf:
        soapbridge: DEBUG
spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gxf-proxy

security:
  key-store:
    location: /etc/ssl/certs
    password: 1234
    type: pkcs12
  trust-store:
    location: /etc/ssl/certs/trust.jks
    password: 123456
    type: jks
  signing:
    key-type: RSA
    sign-key-file: /etc/ssl/certs/proxy-server/sign-key.der
    verify-key-file: /etc/ssl/certs/proxy-server/verify-key.der
    provider: SunRsaSign
    signature: SHA256withRSA

kafka:
  outgoing:
    requests:
      topic: proxy-server-calls-requests
    responses:
      topic: proxy-server-calls-responses
  incoming:
    requests:
      topic: proxy-server-notification-requests
      concurrency: 1
    responses:
      topic: proxy-server-notification-responses
      concurrency: 1

soap:
  call-endpoint:
    host: localhost
    port: 443
    protocol: https
  time-out: 45

management:
  server:
    port: 8888
  #    ssl:
  #      enabled: false
  #      client-auth: none
  endpoints:
    web:
      exposure:
        include: health
