logging:
  level:
    org:
      gxf:
        soapbridge: DEBUG

spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: gxf-proxy

proxy-server:
    network-zone: IT

security:
  key-store:
    location: /etc/ssl/certs
    password: 1234
    type: pkcs12
  trust-store:
    location: /etc/ssl/certs/trust.jks
    password: 123456
    type: jks
  signing:
    key-type: RSA
    sign-key-file: /etc/ssl/certs/proxy-server/sign-key.der
    verify-key-file: /etc/ssl/certs/proxy-server/verify-key.der
    provider: SunRsaSign
    signature: SHA256withRSA

topics:
    calls:
        requests: proxy-server-calls-requests
        responses: proxy-server-calls-responses
    notifications:
        requests: proxy-server-notification-requests
        responses: proxy-server-notification-responses

soap:
    notification:
        host: localhost
        port: 443
        protocol: https
    platform:
        host: localhost
        port: 443
        protocol: https
    hostname-verification-strategy: BROWSER_COMPATIBLE_HOSTNAMES
    time-out: 45
    custom-timeouts: SetScheduleRequest,180,GetStatusRequest,120
