management:
  endpoints:
    web:
      exposure:
        include: prometheus

soap:
  hostname-verification-strategy: BROWSER_COMPATIBLE_HOSTNAMES

kafka:
  incoming:
    requests:
      concurrency: 1
    responses:
      concurrency: 1